config/routes.rb
Rails.application.routes.draw do
  get 'auth/failure', to: 'sessions#new'

  controller :sessions do
    get '/auth/:provider/callback', action: :create
    get  'login', action: :new
    post 'login', action: :create
    get 'logout', action: :destroy
  end

  resources :lists do
    resources :tasks do
      patch :complete, on: :member
    end
  end

  root to: 'lists#index'
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :title, :user, presence: true
  validates :title, length: { maximum: 200 }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list

  validates :list, :description, presence: true
  validates :description, length: { maximum: 200 }

  def completed?
    completed_at.present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists, dependent: :destroy
  has_many :tasks, through: :lists

  before_validation :set_permalink

  validates :name, :email, :permalink, presence: true
  validates :permalink, uniqueness: { allow_blank: true, case_sensitive: false }

  private

    def set_permalink
      self.permalink = self.email.split('@').first
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authorize
  helper_method :current_user

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { render nothing: true, status: 403 }
      format.html { redirect_to root_url, flash: { error: t(:access_denied) } }
    end
  end

  private

    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    def authorize
      redirect_to login_url, alert: t(:access_denied) unless current_user
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :load_list, except: [:new, :create, :index]
  before_action :load_user, only: :create

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = @user.lists.create(lists_params)
    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: t(:resource_created, resource: 'List') }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: t(:resouce_updated, resource: 'List') }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: t(:resource_destroyed, resource: 'List') }
      format.json { head :no_content }
    end
  end

  def show; end

  private
    def lists_params
      params.require(:list).permit(:id, :title, tasks_attributes: [:id, :description, :_destroy])
    end

    def load_list
      @list = List.find_by(id: params[:id])
    end

    def load_user
      @user = current_user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :reset_session, only: [:create, :destroy]
  before_action :set_or_create_user, only: :create

  skip_before_action :authorize

  def new; end

  def create
    session[:user_id] = @user.id if @user.present?
    if session[:user_id]
      redirect_to root_url, notice: t(:login_successful)
    else
      redirect_to login_url, alert: t(:login_failure)
    end
  end

  def destroy
    redirect_to login_url, notice: t(:logout_successful)
  end

  private

    def set_or_create_user
      if (extract_email)
        @user = User.find_by(email: @email) || User.create(name: @auth['info']['name'],
          email: @email
        )
      end
    end

    def extract_email
      @auth = request.env["omniauth.auth"]
      @email = @auth["info"]["email"] if @auth['info']
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :load_list, only: [:create, :destroy, :complete]
  before_action :load_task, only: [:destroy, :complete]

  def create
    @task = @list.tasks.create(tasks_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to @list, notice: t(:resource_created, resource: 'Task') }
        format.js
      else
        format.html redirect_to @list, notice: t(:resource_not_created, resource: 'Task')
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @task.destroy
        format.json { render json: { notice: t(:resource_destroyed, resource: 'Task') }, status: 200 }
      else
        format.json { render json: @task.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def complete
    respond_to do |format|
      @task.update_attribute(:completed_at, Time.current)
      format.json { render json: { notice: t(:task_completed) }, status: 200 }
    end
  end

  private
    def load_list
      @list = List.find_by(id: params[:list_id])
      render json: { errors: [t(:resource_not_found, resource: 'List')] }, status: 404 unless @list
    end

    def load_task
      @task = Task.find_by(id: params[:id])
      render json: { errors: [t(:resource_not_found, resource: 'Task')] }, status: 404 unless @task
    end

    def tasks_params
      params.require(:task).permit(:id, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def google_oauth_path
    "/auth/google_oauth2"
  end
end

app/views/application/_flashes.html.erb
<div class="message">
  <p id="notice">
    <% if flash[:alert] %>
      <%= flash[:alert] %>
    <% end %>

    <% if flash[:error] %>
      <%= flash[:error] %>
    <% end %>

    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolist</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,300,700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= yield :head %>
</head>
<body class='<%= controller.controller_name %>'>
  <div>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "To Do List", root_path, class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to 'Help', '' %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user.present? %>
              <li><%= link_to "Sign Out", logout_path %></li>
            <% else %>
              <li><%= link_to "Sign in with Gmail Id", google_oauth_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </div>

  <div class="container">
    <%= yield %>
  </div>

  <%= yield :footer %>
</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>
      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, 'Title:' %>
    <%= f.text_field :title, { maxlength: '200' } %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1 class="todo_list_title">Edit List</h1>

<div class="forms">
  <%= render 'form' %>
</div>

<div class="links">
  <%= link_to 'Cancel', lists_url %>
</div>

app/views/lists/index.html.erb
<% @lists.each do |list| %>
  <div class="index_row clearfix">
    <h2 class="todo_list_title"><%= link_to list.title, list_url(list) %></h2>
  </div>
<% end %>

<div class="links">
  <%= link_to "Create New List", new_list_url %>
</div>

app/views/lists/new.html.erb
<h1 class="todo_list_title">New List</h1>

<div class="forms">
  <%= render 'form' %>
</div>

<div class="links">
  <%= link_to 'Cancel', lists_url, class: "btn btn-default" %>
</div>

app/views/lists/show.html.erb
<%= render 'flashes' %>
<h2 class="todo_list_title"><%= @list.title %></h2>
<div id="tasks_wrapper">
  <div class="tasks-container">
    <%= render @list.tasks %>
  </div>
  <div id="form">
    <%= render 'tasks/form' %>
  </div>
</div>
<div class="links">
  <%= link_to 'Edit', edit_list_url(@list) %> |
  <%= link_to 'Delete', list_path(@list), method: :delete, data: { confirm: t(:confirm_delete) } %> |
  <%= link_to 'Back', lists_url %>
</div>
<%= content_for :footer do %>
  <%= javascript_include_tag "tasks/index" %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for [@list, @list.tasks.build], { url: list_tasks_url(@list), remote: true, method: :post, data: { class: 'tasks-form' } } do |f| %>
	<%= f.text_field :description, placeholder: "New Task", class: 'task-description' %>
	<%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<div class="row clearfix" data-task="true">
  <div class="complete">
    <%= link_to 'javascript:void(0)', data: { class: 'mark-completed-btn', id: task.id, url: complete_list_task_url(@list, task), method: :patch } do %>
      <i class="40-perc-opactity fa fa-check"></i>
    <% end %>
  </div>
  <div class="task">
    <% if task.completed? %>
      <p class="40-perc-opactity task-description strike-through"><%= task.description %></p>
    <% else %>
      <p class="task-description"><%= task.description %></p>
    <% end %>
  </div>
  <div class="trash">
    <%= link_to 'javascript:void(0)', data: { confirm_message: t(:confirm_delete), class: 'trash-btn', id: task.id, url: list_task_url(@list, task), method: :delete } do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </div>
</div>

app/views/tasks/create.js.erb
$('#tasks_wrapper .tasks-container').append("<%= escape_javascript render(@task) %>");
$('[data-class="tasks-form"] .task-description').val('');